version: "3"

services:
  wordpress:
    container_name: wordpress
    image: wordpress:fpm-alpine
    environment:
      FS_METHOD: direct
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: ${DB_HOST:-mariadb}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-mySecret123}
    volumes:
      - files:/var/www/html
      - .:/var/www/html/wp-content/plugins/instagram-scraper
    depends_on:
      - mariadb
      - nginx

  mariadb:
    container_name: mariadb
    image: mariadb:10
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-mySecret123}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - data:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    volumes:
      - files:/var/www/html
      - .:/var/www/html/wp-content/plugins/instagram-scraper
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

volumes:
  files:
  data:
